### ISSUE TITLE
Change the repo to be a Fork

### ISSUE THREAD

**Issue by tqchen** [javelinjs/mxnet-scala#2]
It might be interesting to work this as a fork of original repo so the commit history of contributors could be merged back when it is ready to become part of main repo. You can rename the forked repo as mxnet-scala

**Comment by terrytangyuan** [comment]
@javelinjs is doing some code cleaning and setup right now so I am still on hold. Do you mean we should both work on our separate fork, then merge changes to this repo, and finally merge to main repo?

**Comment by tqchen** [comment]
Yes, that is what I mean. The benefit of working on a fork is the contribution history of the contributors will remain there when merged back.  I am fine with either case though, just a suggestion

**Comment by terrytangyuan** [comment]
Ok thanks! We'll discuss that.

**Comment by javelinjs** [comment]
@tqchen thank you for your suggestion. @terrytangyuan mind having a chat maybe 7 hours later?

**Comment by terrytangyuan** [comment]
That works for me.

**Comment by tqchen** [comment]
Also if the repo is changed to a fork, consider rename the folder to be scala or scala-package to consistent with other language packages

**Comment by terrytangyuan** [comment]
@tqchen Sure, done.

**Comment by yzhliu** [comment]
We move to https://github.com/terrytangyuan/mxnet/tree/master/scala-package
