### ISSUE TITLE
JNI C code style check & format

### ISSUE THREAD

**Issue by yzhliu** [javelinjs/mxnet-scala#6]
We need to define a JNI c style

**Comment by yanqingmen** [comment]
@javelinjs hi, can we use the cpplint (which used in Makefile) to do style check? This could be done by simply add the code folder path to Makefile's lint part. Then we can do style check by 'Make lint'

**Comment by yzhliu** [comment]
I'm afraid it is not that easy. The google style may not be suitable for JNI c code, e.g. we usually start a new line for function arguments,  the types are camel-casing, and we always have function names like 'Java_ml_dmlc_mxnet_LibInfo_mxKVStoreSetUpdater', etc.

**Comment by yanqingmen** [comment]
yeah, you are right. We need find style suitable for JNI C code

**Comment by tqchen** [comment]
The linter used by dmlc is customized in  https://github.com/dmlc/dmlc-core/blob/master/scripts/lint.py

We can add a customized option to disable the warning(e.g. function name)
